apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    run: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kibana
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
      - name: kibana
        #image: docker.elastic.co/kibana/kibana:6.5.4
        image: elyes000/logtrail:logtrailforkibana
        volumeMounts:
          - name: logtrail-config
            mountPath: /config
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200/
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        #- name: CLUSTER_NAME
         # value: elasticsearch
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
      volumes:
        - name: logtrail-config
          configMap:
            name: logtrail-config
            


---

apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    #service: kibana
    run: kibana
spec:
  type: NodePort
  selector:
    run: kibana
  ports:
  - port: 5601
    targetPort: 5601

